CREATE TABLE public.wedding_domains (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    hostname text NOT NULL UNIQUE,
    is_primary boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT wedding_domains_hostname_normalized CHECK (
        hostname = lower(btrim(hostname))
        AND hostname !~ '[:/[:space:]]'
        AND length(hostname) BETWEEN 1 AND 253
    )
);

CREATE INDEX wedding_domains_wedding_id_idx
    ON public.wedding_domains(wedding_id);

CREATE UNIQUE INDEX wedding_domains_one_primary_per_wedding_idx
    ON public.wedding_domains(wedding_id)
    WHERE is_primary;

ALTER TABLE public.wedding_domains ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.wedding_domains FROM anon, authenticated;
GRANT SELECT ON public.wedding_domains TO wedding_worker;

CREATE POLICY wedding_domains_worker_select
ON public.wedding_domains FOR SELECT TO wedding_worker
USING (true);
