-- FantaSposi foundation. Game participation is intentionally separate from
-- wedding_members, whose existing role is limited to wedding administration.

ALTER TABLE public.profiles
ADD COLUMN avatar_url text;

CREATE TABLE public.fantasposi_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    team text NOT NULL CHECK (team IN ('bride', 'groom')),
    onboarding_completed boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    joined_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (wedding_id, user_id),
    UNIQUE (id, wedding_id)
);

CREATE TABLE public.fantasposi_phases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    code text NOT NULL,
    name text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    starts_at timestamptz,
    ends_at timestamptz,
    status text NOT NULL DEFAULT 'locked'
        CHECK (status IN ('locked', 'active', 'completed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at),
    UNIQUE (wedding_id, code),
    UNIQUE (id, wedding_id)
);

CREATE TABLE public.fantasposi_missions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    phase_id bigint NOT NULL,
    code text NOT NULL,
    title text NOT NULL,
    description text,
    mission_type text NOT NULL
        CHECK (mission_type IN ('action', 'photo', 'social', 'live', 'automatic')),
    points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
    active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (phase_id, wedding_id)
        REFERENCES public.fantasposi_phases(id, wedding_id) ON DELETE CASCADE,
    UNIQUE (wedding_id, code),
    UNIQUE (id, wedding_id)
);

CREATE TABLE public.fantasposi_predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    phase_id bigint,
    code text NOT NULL,
    question text NOT NULL,
    prediction_type text NOT NULL
        CHECK (prediction_type IN ('choice', 'number', 'text', 'time', 'boolean')),
    options jsonb,
    points integer NOT NULL DEFAULT 0 CHECK (points >= 0),
    locks_at timestamptz,
    active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (phase_id, wedding_id)
        REFERENCES public.fantasposi_phases(id, wedding_id) ON DELETE CASCADE,
    UNIQUE (wedding_id, code),
    UNIQUE (id, wedding_id)
);

CREATE TABLE public.fantasposi_player_missions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    player_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'available'
        CHECK (status IN ('available', 'claimed', 'completed', 'rejected')),
    claimed_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (player_id, wedding_id)
        REFERENCES public.fantasposi_players(id, wedding_id) ON DELETE CASCADE,
    FOREIGN KEY (mission_id, wedding_id)
        REFERENCES public.fantasposi_missions(id, wedding_id) ON DELETE CASCADE,
    UNIQUE (player_id, mission_id)
);

CREATE TABLE public.fantasposi_player_predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    player_id bigint NOT NULL,
    prediction_id bigint NOT NULL,
    answer jsonb NOT NULL,
    status text NOT NULL DEFAULT 'submitted'
        CHECK (status IN ('submitted', 'scored')),
    points_awarded integer CHECK (points_awarded IS NULL OR points_awarded >= 0),
    submitted_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (player_id, wedding_id)
        REFERENCES public.fantasposi_players(id, wedding_id) ON DELETE CASCADE,
    FOREIGN KEY (prediction_id, wedding_id)
        REFERENCES public.fantasposi_predictions(id, wedding_id) ON DELETE CASCADE,
    UNIQUE (player_id, prediction_id)
);

CREATE INDEX idx_fantasposi_players_user
    ON public.fantasposi_players(user_id);
CREATE INDEX idx_fantasposi_players_wedding_active
    ON public.fantasposi_players(wedding_id, active);
CREATE INDEX idx_fantasposi_players_wedding_team
    ON public.fantasposi_players(wedding_id, team) WHERE active;
CREATE INDEX idx_fantasposi_phases_wedding_order
    ON public.fantasposi_phases(wedding_id, sort_order, id);
CREATE INDEX idx_fantasposi_phases_wedding_status
    ON public.fantasposi_phases(wedding_id, status);
CREATE INDEX idx_fantasposi_missions_wedding_phase
    ON public.fantasposi_missions(wedding_id, phase_id, active, sort_order, id);
CREATE INDEX idx_fantasposi_predictions_wedding_phase
    ON public.fantasposi_predictions(wedding_id, phase_id, active, sort_order, id);
CREATE INDEX idx_fantasposi_player_missions_player_status
    ON public.fantasposi_player_missions(player_id, status);
CREATE INDEX idx_fantasposi_player_predictions_player
    ON public.fantasposi_player_predictions(player_id);

ALTER TABLE public.fantasposi_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasposi_phases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasposi_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasposi_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasposi_player_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fantasposi_player_predictions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON
    public.fantasposi_players,
    public.fantasposi_phases,
    public.fantasposi_missions,
    public.fantasposi_predictions,
    public.fantasposi_player_missions,
    public.fantasposi_player_predictions
FROM anon, authenticated;

GRANT SELECT ON public.fantasposi_players TO authenticated;
GRANT SELECT ON
    public.fantasposi_phases,
    public.fantasposi_missions,
    public.fantasposi_predictions,
    public.fantasposi_player_missions,
    public.fantasposi_player_predictions
TO authenticated;

CREATE POLICY fantasposi_players_read_own
ON public.fantasposi_players FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY fantasposi_phases_read_for_player
ON public.fantasposi_phases FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.fantasposi_players player
    WHERE player.wedding_id = fantasposi_phases.wedding_id
      AND player.user_id = (SELECT auth.uid())
      AND player.active
));

CREATE POLICY fantasposi_missions_read_for_player
ON public.fantasposi_missions FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.fantasposi_players player
    WHERE player.wedding_id = fantasposi_missions.wedding_id
      AND player.user_id = (SELECT auth.uid())
      AND player.active
));

CREATE POLICY fantasposi_predictions_read_for_player
ON public.fantasposi_predictions FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.fantasposi_players player
    WHERE player.wedding_id = fantasposi_predictions.wedding_id
      AND player.user_id = (SELECT auth.uid())
      AND player.active
));

CREATE POLICY fantasposi_player_missions_read_own
ON public.fantasposi_player_missions FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.fantasposi_players player
    WHERE player.id = fantasposi_player_missions.player_id
      AND player.wedding_id = fantasposi_player_missions.wedding_id
      AND player.user_id = (SELECT auth.uid())
));

CREATE POLICY fantasposi_player_predictions_read_own
ON public.fantasposi_player_predictions FOR SELECT TO authenticated
USING (EXISTS (
    SELECT 1 FROM public.fantasposi_players player
    WHERE player.id = fantasposi_player_predictions.player_id
      AND player.wedding_id = fantasposi_player_predictions.wedding_id
      AND player.user_id = (SELECT auth.uid())
));

GRANT SELECT, INSERT, UPDATE ON public.profiles TO wedding_worker;
GRANT SELECT, INSERT, UPDATE ON public.fantasposi_players TO wedding_worker;
GRANT SELECT ON public.fantasposi_phases TO wedding_worker;
GRANT USAGE, SELECT ON SEQUENCE public.fantasposi_players_id_seq TO wedding_worker;

CREATE POLICY profiles_worker_insert ON public.profiles
FOR INSERT TO wedding_worker WITH CHECK (true);
CREATE POLICY profiles_worker_update ON public.profiles
FOR UPDATE TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY fantasposi_players_worker_all ON public.fantasposi_players
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY fantasposi_phases_worker_select ON public.fantasposi_phases
FOR SELECT TO wedding_worker USING (true);
