-- PostgreSQL schema equivalent to the legacy Cloudflare D1 migrations 0001-0010.
-- Binary media remain in Cloudflare R2; these tables store metadata and content only.

CREATE TABLE public.app_config (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE public.weddings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    bride_name text NOT NULL,
    groom_name text NOT NULL,
    wedding_date date NOT NULL,
    status text NOT NULL DEFAULT 'active',
    theme text,
    hero_eyebrow text,
    hero_title text,
    hero_subtitle text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL UNIQUE,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    source text NOT NULL,
    original_filename text,
    original_key text NOT NULL,
    preview_key text,
    thumbnail_key text,
    mime_type text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    width integer,
    height integer,
    sha256 text,
    status text NOT NULL DEFAULT 'uploading',
    preview_status text NOT NULL DEFAULT 'pending',
    preview_error text,
    preview_generated_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    uploaded_at timestamptz,
    UNIQUE (id, wedding_id)
);

CREATE INDEX idx_media_wedding_id ON public.media(wedding_id);
CREATE INDEX idx_media_status ON public.media(status);
CREATE INDEX idx_media_source ON public.media(source);
CREATE INDEX idx_media_created_at ON public.media(created_at);

CREATE TABLE public.site_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid uuid NOT NULL UNIQUE,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    asset_type text NOT NULL DEFAULT 'other'
        CHECK (asset_type IN ('hero', 'story', 'location', 'info', 'other')),
    original_filename text,
    original_key text NOT NULL,
    optimized_key text,
    mime_type text NOT NULL,
    size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes >= 0),
    width integer,
    height integer,
    status text NOT NULL DEFAULT 'uploading'
        CHECK (status IN ('uploading', 'processing', 'ready', 'failed')),
    created_at timestamptz NOT NULL DEFAULT now(),
    uploaded_at timestamptz,
    processed_at timestamptz,
    UNIQUE (id, wedding_id)
);

CREATE INDEX idx_site_assets_wedding_id ON public.site_assets(wedding_id);
CREATE INDEX idx_site_assets_asset_type ON public.site_assets(asset_type);
CREATE INDEX idx_site_assets_status ON public.site_assets(status);

CREATE TABLE public.wedding_settings (
    wedding_id bigint PRIMARY KEY REFERENCES public.weddings(id),
    gallery_enabled boolean NOT NULL DEFAULT true,
    gallery_preview_enabled boolean NOT NULL DEFAULT true,
    gallery_download_enabled boolean NOT NULL DEFAULT true,
    guest_uploads_enabled boolean NOT NULL DEFAULT true,
    require_guest_approval boolean NOT NULL DEFAULT true,
    photobooth_auto_approve boolean NOT NULL DEFAULT true,
    schedule_enabled boolean NOT NULL DEFAULT true,
    locations_enabled boolean NOT NULL DEFAULT true,
    info_enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.wedding_home_content (
    wedding_id bigint PRIMARY KEY REFERENCES public.weddings(id),
    story_enabled boolean NOT NULL DEFAULT true,
    story_eyebrow text,
    story_title text,
    story_intro text,
    story_quote text,
    story_quote_author text,
    hero_site_asset_id bigint REFERENCES public.site_assets(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (hero_site_asset_id, wedding_id)
        REFERENCES public.site_assets(id, wedding_id)
);

CREATE TABLE public.wedding_schedule (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    time_label text NOT NULL,
    title text NOT NULL,
    subtitle text,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE public.wedding_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    name text NOT NULL,
    type text,
    address text,
    maps_url text,
    description text,
    photo_media_id bigint REFERENCES public.media(id) ON DELETE SET NULL,
    photo_site_asset_id bigint REFERENCES public.site_assets(id) ON DELETE SET NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    FOREIGN KEY (photo_media_id, wedding_id)
        REFERENCES public.media(id, wedding_id),
    FOREIGN KEY (photo_site_asset_id, wedding_id)
        REFERENCES public.site_assets(id, wedding_id)
);

CREATE TABLE public.wedding_info_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    category text NOT NULL,
    title text NOT NULL,
    content text,
    image_site_asset_id bigint REFERENCES public.site_assets(id) ON DELETE SET NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    FOREIGN KEY (image_site_asset_id, wedding_id)
        REFERENCES public.site_assets(id, wedding_id)
);

CREATE TABLE public.wedding_story_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id),
    year_label text,
    title text NOT NULL,
    body text,
    photo_media_id bigint REFERENCES public.media(id) ON DELETE SET NULL,
    photo_site_asset_id bigint REFERENCES public.site_assets(id) ON DELETE SET NULL,
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (photo_media_id, wedding_id)
        REFERENCES public.media(id, wedding_id),
    FOREIGN KEY (photo_site_asset_id, wedding_id)
        REFERENCES public.site_assets(id, wedding_id)
);

CREATE INDEX idx_wedding_schedule_public
    ON public.wedding_schedule(wedding_id, enabled, sort_order, id);
CREATE INDEX idx_wedding_locations_public
    ON public.wedding_locations(wedding_id, enabled, sort_order, id);
CREATE INDEX idx_wedding_info_items_public
    ON public.wedding_info_items(wedding_id, enabled, sort_order, id);
CREATE INDEX idx_wedding_story_items_wedding_id
    ON public.wedding_story_items(wedding_id);
CREATE INDEX idx_wedding_story_items_order
    ON public.wedding_story_items(wedding_id, sort_order, id);

CREATE TABLE public.profiles (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name text,
    system_role text CHECK (system_role IS NULL OR system_role = 'super_admin'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.wedding_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id bigint NOT NULL REFERENCES public.weddings(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role = 'wedding_admin'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (wedding_id, user_id)
);

CREATE INDEX idx_wedding_members_user_id ON public.wedding_members(user_id);
CREATE INDEX idx_wedding_members_wedding_id ON public.wedding_members(wedding_id);

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    INSERT INTO public.profiles (user_id, display_name)
    VALUES (NEW.id, coalesce(NEW.raw_user_meta_data ->> 'display_name', NEW.email))
    ON CONFLICT (user_id) DO NOTHING;
    RETURN NEW;
END;
$$;

CREATE TRIGGER create_profile_after_auth_user
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

INSERT INTO public.profiles (user_id, display_name)
SELECT id, coalesce(raw_user_meta_data ->> 'display_name', email)
FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

-- Application data is mediated by the Worker. Browser roles default to deny;
-- wedding_worker has only the table privileges needed by the Worker.
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_home_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_info_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_story_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wedding_members ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON
    public.app_config,
    public.weddings,
    public.media,
    public.site_assets,
    public.wedding_settings,
    public.wedding_home_content,
    public.wedding_schedule,
    public.wedding_locations,
    public.wedding_info_items,
    public.wedding_story_items,
    public.profiles,
    public.wedding_members
FROM anon, authenticated;
GRANT SELECT ON public.profiles, public.wedding_members TO authenticated;

CREATE POLICY profiles_read_own
ON public.profiles FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

CREATE POLICY wedding_members_read_own
ON public.wedding_members FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = user_id);

REVOKE ALL ON FUNCTION public.handle_new_auth_user() FROM PUBLIC, anon, authenticated;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wedding_worker') THEN
        CREATE ROLE wedding_worker LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
    END IF;
END;
$$;

GRANT USAGE ON SCHEMA public TO wedding_worker;
GRANT SELECT ON public.app_config, public.profiles, public.wedding_members TO wedding_worker;
GRANT SELECT, UPDATE ON public.weddings TO wedding_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    public.media,
    public.site_assets,
    public.wedding_settings,
    public.wedding_home_content,
    public.wedding_schedule,
    public.wedding_locations,
    public.wedding_info_items,
    public.wedding_story_items
TO wedding_worker;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO wedding_worker;

CREATE POLICY app_config_worker_select ON public.app_config
FOR SELECT TO wedding_worker USING (true);
CREATE POLICY weddings_worker_select ON public.weddings
FOR SELECT TO wedding_worker USING (true);
CREATE POLICY weddings_worker_update ON public.weddings
FOR UPDATE TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY media_worker_all ON public.media
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY site_assets_worker_all ON public.site_assets
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_settings_worker_all ON public.wedding_settings
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_home_content_worker_all ON public.wedding_home_content
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_schedule_worker_all ON public.wedding_schedule
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_locations_worker_all ON public.wedding_locations
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_info_items_worker_all ON public.wedding_info_items
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY wedding_story_items_worker_all ON public.wedding_story_items
FOR ALL TO wedding_worker USING (true) WITH CHECK (true);
CREATE POLICY profiles_worker_select ON public.profiles
FOR SELECT TO wedding_worker USING (true);
CREATE POLICY wedding_members_worker_select ON public.wedding_members
FOR SELECT TO wedding_worker USING (true);

CREATE OR REPLACE FUNCTION public.reset_backend_sequences()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    table_name text;
    maximum_id bigint;
    sequence_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'weddings', 'media', 'site_assets', 'wedding_schedule', 'wedding_locations',
        'wedding_info_items', 'wedding_story_items', 'wedding_members'
    ] LOOP
        EXECUTE format('SELECT max(id) FROM public.%I', table_name) INTO maximum_id;
        sequence_name := pg_get_serial_sequence('public.' || table_name, 'id');
        IF sequence_name IS NOT NULL THEN
            PERFORM setval(sequence_name, coalesce(maximum_id, 1), maximum_id IS NOT NULL);
        END IF;
    END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.reset_backend_sequences() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reset_backend_sequences() TO service_role;
